CREATE TABLE source_images (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id NUMBER NOT NULL,
  user_id NUMBER NOT NULL,
  original_filename VARCHAR2(255) NOT NULL,
  stored_name VARCHAR2(320) NOT NULL,
  content_type VARCHAR2(100) NOT NULL,
  byte_size NUMBER NOT NULL,
  width_px NUMBER,
  height_px NUMBER,
  sha256_hex VARCHAR2(64) NOT NULL,
  retention_status VARCHAR2(32) DEFAULT 'active' NOT NULL,
  image_blob BLOB NOT NULL,
  uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  deleted_at TIMESTAMP WITH TIME ZONE,
  CONSTRAINT fk_source_images_project_id
    FOREIGN KEY (project_id) REFERENCES room_projects(id),
  CONSTRAINT fk_source_images_user_id
    FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT chk_source_images_retention_status
    CHECK (retention_status IN ('active', 'scheduled_delete', 'deleted')),
  CONSTRAINT chk_source_images_content_type
    CHECK (content_type IN ('image/jpeg', 'image/png', 'image/webp')),
  CONSTRAINT chk_source_images_byte_size
    CHECK (byte_size > 0)
);

CREATE INDEX idx_source_images_project_id ON source_images(project_id);
CREATE INDEX idx_source_images_user_id_project_id ON source_images(user_id, project_id);

CREATE TABLE room_project_dimensions (
  project_id NUMBER NOT NULL,
  user_id NUMBER NOT NULL,
  width_value NUMBER(10, 3) NOT NULL,
  depth_value NUMBER(10, 3) NOT NULL,
  height_value NUMBER(10, 3) NOT NULL,
  unit VARCHAR2(16) DEFAULT 'meters' NOT NULL,
  height_source VARCHAR2(16) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_room_project_dimensions PRIMARY KEY (project_id, user_id),
  CONSTRAINT fk_room_dimensions_project_id
    FOREIGN KEY (project_id) REFERENCES room_projects(id),
  CONSTRAINT fk_room_dimensions_user_id
    FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT chk_room_dimensions_unit
    CHECK (unit IN ('meters')),
  CONSTRAINT chk_room_dimensions_height_source
    CHECK (height_source IN ('user', 'default')),
  CONSTRAINT chk_room_dimensions_positive_values
    CHECK (width_value > 0 AND depth_value > 0 AND height_value > 0)
);

CREATE INDEX idx_room_dimensions_user_id ON room_project_dimensions(user_id);
