CREATE TABLE reconstruction_jobs (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id NUMBER NOT NULL,
  user_id NUMBER NOT NULL,
  source_image_id NUMBER NOT NULL,
  status VARCHAR2(32) DEFAULT 'created' NOT NULL,
  provider VARCHAR2(64) DEFAULT 'browser-opencv' NOT NULL,
  retry_of_job_id NUMBER,
  failure_reason_code VARCHAR2(64),
  failure_reason_message VARCHAR2(1000),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_reconstruction_jobs_project_id
    FOREIGN KEY (project_id) REFERENCES room_projects(id),
  CONSTRAINT fk_reconstruction_jobs_user_id
    FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_reconstruction_jobs_source_image_id
    FOREIGN KEY (source_image_id) REFERENCES source_images(id),
  CONSTRAINT fk_reconstruction_jobs_retry_of_job_id
    FOREIGN KEY (retry_of_job_id) REFERENCES reconstruction_jobs(id),
  CONSTRAINT chk_reconstruction_jobs_status
    CHECK (status IN (
      'created',
      'uploading',
      'processing',
      'review_required',
      'succeeded',
      'failed',
      'timeout',
      'cancelled',
      'retrying'
    ))
);

CREATE INDEX idx_reconstruction_jobs_user_project
  ON reconstruction_jobs(user_id, project_id);
CREATE INDEX idx_reconstruction_jobs_status
  ON reconstruction_jobs(status);

CREATE TABLE reconstruction_job_transitions (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id NUMBER NOT NULL,
  status VARCHAR2(32) NOT NULL,
  actor VARCHAR2(32) NOT NULL,
  reason_code VARCHAR2(64),
  reason_message VARCHAR2(1000),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_reconstruction_job_transitions_job_id
    FOREIGN KEY (job_id) REFERENCES reconstruction_jobs(id),
  CONSTRAINT chk_reconstruction_transitions_status
    CHECK (status IN (
      'created',
      'uploading',
      'processing',
      'review_required',
      'succeeded',
      'failed',
      'timeout',
      'cancelled',
      'retrying'
    ))
);

CREATE INDEX idx_reconstruction_transitions_job
  ON reconstruction_job_transitions(job_id, created_at);
