CREATE TABLE confirmed_geometries (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id NUMBER NOT NULL,
  user_id NUMBER NOT NULL,
  opencv_result_id NUMBER,
  coordinate_space VARCHAR2(32) NOT NULL,
  geometry_kind VARCHAR2(32) NOT NULL,
  points_json CLOB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_confirmed_geometries_project_id
    FOREIGN KEY (project_id) REFERENCES room_projects(id),
  CONSTRAINT fk_confirmed_geometries_user_id
    FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_confirmed_geometries_opencv_result_id
    FOREIGN KEY (opencv_result_id) REFERENCES opencv_results(id),
  CONSTRAINT chk_confirmed_geometries_coordinate_space
    CHECK (coordinate_space IN ('image_pixels')),
  CONSTRAINT chk_confirmed_geometries_geometry_kind
    CHECK (geometry_kind IN ('room_boundary'))
);

CREATE INDEX idx_confirmed_geometries_user_project
  ON confirmed_geometries(user_id, project_id);
CREATE INDEX idx_confirmed_geometries_opencv_result
  ON confirmed_geometries(opencv_result_id);
