CREATE TABLE floor_plans (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id NUMBER NOT NULL,
  user_id NUMBER NOT NULL,
  confirmed_geometry_id NUMBER NOT NULL,
  unit VARCHAR2(16) DEFAULT 'meters' NOT NULL,
  width_value NUMBER(10, 3) NOT NULL,
  depth_value NUMBER(10, 3) NOT NULL,
  width_deviation_ratio NUMBER(8, 6) DEFAULT 0 NOT NULL,
  depth_deviation_ratio NUMBER(8, 6) DEFAULT 0 NOT NULL,
  aspect_ratio_error NUMBER(8, 6) DEFAULT 0 NOT NULL,
  perspective_assumptions_json CLOB NOT NULL,
  image_geometry_json CLOB NOT NULL,
  metric_geometry_json CLOB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_floor_plans_project_id
    FOREIGN KEY (project_id) REFERENCES room_projects(id),
  CONSTRAINT fk_floor_plans_user_id
    FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_floor_plans_confirmed_geometry_id
    FOREIGN KEY (confirmed_geometry_id) REFERENCES confirmed_geometries(id),
  CONSTRAINT chk_floor_plans_unit
    CHECK (unit IN ('meters')),
  CONSTRAINT chk_floor_plans_deviation
    CHECK (
      width_deviation_ratio <= 0.05
      AND depth_deviation_ratio <= 0.05
      AND aspect_ratio_error <= 0.05
    )
);

CREATE INDEX idx_floor_plans_user_project ON floor_plans(user_id, project_id);
CREATE INDEX idx_floor_plans_confirmed_geometry ON floor_plans(confirmed_geometry_id);
