CREATE TABLE layouts (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id NUMBER NOT NULL,
  user_id NUMBER NOT NULL,
  room_dimensions_json CLOB CHECK (room_dimensions_json IS JSON) NOT NULL,
  floor_plan_json CLOB CHECK (floor_plan_json IS JSON) NOT NULL,
  source_metadata_json CLOB CHECK (source_metadata_json IS JSON) NOT NULL,
  furniture_objects_json CLOB CHECK (furniture_objects_json IS JSON) NOT NULL,
  editor_scene_json CLOB CHECK (editor_scene_json IS JSON) NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_layouts_project_id
    FOREIGN KEY (project_id) REFERENCES room_projects(id),
  CONSTRAINT fk_layouts_user_id
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_layouts_project_user ON layouts(project_id, user_id);
